ALTER TABLE DIM_Product
ADD productsSK_PK INT IDENTITY(1,1);

ALTER TABLE DIM_Supplier
ADD SupplierSK_PK INT IDENTITY(1,1);

ALTER TABLE Dim_Customer
ADD CustomerSK_PK INT IDENTITY(1,1);

ALTER TABLE Dim_Employee
ADD EmployeeSK_PK INT IDENTITY(1,1);

ALTER TABLE Dim_ShipInfo
ADD ShipInfoSK_PK INT IDENTITY(1,1);

ALTER TABLE Dim_Shipper
ADD ShipperSK_PK INT IDENTITY(1,1);